#ifndef GUARD_CONSTANTS_HEAL_LOCATIONS_H
#define GUARD_CONSTANTS_HEAL_LOCATIONS_H

#define HEAL_LOCATION_DRAYNOR 1
#define HEAL_LOCATION_PORT_SARIM 2
#define HEAL_LOCATION_RIMMINGTON 3
#define HEAL_LOCATION_FALADOR 4
#define HEAL_LOCATION_FALADOR2 5
#define HEAL_LOCATION_VARROCK 6
#define HEAL_LOCATION_VARROCK_NORTH 7
#define HEAL_LOCATION_BARBARIAN_VILLAGE 8
#define HEAL_LOCATION_GOBLIN_VILLAGE 9
#define HEAL_LOCATION_DWARVEN_MINES 10
#define HEAL_LOCATION_EDGEVILLE 11
#define HEAL_LOCATION_AL_KHARID 12
#define HEAL_LOCATION_LUMBRIDGE 13
#define HEAL_LOCATION_TUTORIAL_ISLAND 14
#define HEAL_LOCATION_YANILLE 15
#define HEAL_LOCATION_ARDOUGNE 16
#define HEAL_LOCATION_RELLEKKA 17

#endif // GUARD_CONSTANTS_HEAL_LOCATIONS_H
