#ifndef GUARD_CONSTANTS_MAP_GROUPS_H
#define GUARD_CONSTANTS_MAP_GROUPS_H

//
// DO NOT MODIFY THIS FILE! It is auto-generated from data/maps/map_groups.json
//

// Map Group 0
#define MAP_PETALBURG_CITY   (0 | (0 << 8))
#define MAP_MAUVILLE_CITY    (1 | (0 << 8))
#define MAP_RUSTBORO_CITY    (2 | (0 << 8))
#define MAP_FORTREE_CITY     (3 | (0 << 8))
#define MAP_LILYCOVE_CITY    (4 | (0 << 8))
#define MAP_MOSSDEEP_CITY    (5 | (0 << 8))
#define MAP_EVER_GRANDE_CITY (6 | (0 << 8))
#define MAP_LITTLEROOT_TOWN  (7 | (0 << 8))
#define MAP_OLDALE_TOWN      (8 | (0 << 8))
#define MAP_LAVARIDGE_TOWN   (9 | (0 << 8))
#define MAP_FALLARBOR_TOWN   (10 | (0 << 8))
#define MAP_VERDANTURF_TOWN  (11 | (0 << 8))
#define MAP_PACIFIDLOG_TOWN  (12 | (0 << 8))
#define MAP_ROUTE101         (13 | (0 << 8))

// Map Group 1
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_1F    (0 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_BRENDANS_HOUSE_2F    (1 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_1F        (2 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_MAYS_HOUSE_2F        (3 | (1 << 8))
#define MAP_LITTLEROOT_TOWN_PROFESSOR_BIRCHS_LAB (4 | (1 << 8))

// Map Group 2
#define MAP_OLDALE_TOWN_HOUSE1            (0 | (2 << 8))
#define MAP_OLDALE_TOWN_HOUSE2            (1 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_1F (2 | (2 << 8))
#define MAP_OLDALE_TOWN_POKEMON_CENTER_2F (3 | (2 << 8))
#define MAP_OLDALE_TOWN_MART              (4 | (2 << 8))

// Map Group 3

// Map Group 4

// Map Group 5
#define MAP_FALLARBOR_TOWN_MART                    (0 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_LOBBY       (1 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_CORRIDOR    (2 | (5 << 8))
#define MAP_FALLARBOR_TOWN_BATTLE_TENT_BATTLE_ROOM (3 | (5 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_1F       (4 | (5 << 8))
#define MAP_FALLARBOR_TOWN_POKEMON_CENTER_2F       (5 | (5 << 8))
#define MAP_FALLARBOR_TOWN_COZMOS_HOUSE            (6 | (5 << 8))
#define MAP_FALLARBOR_TOWN_MOVE_RELEARNERS_HOUSE   (7 | (5 << 8))

// Map Group 6
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_LOBBY       (0 | (6 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_CORRIDOR    (1 | (6 << 8))
#define MAP_VERDANTURF_TOWN_BATTLE_TENT_BATTLE_ROOM (2 | (6 << 8))
#define MAP_VERDANTURF_TOWN_MART                    (3 | (6 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_1F       (4 | (6 << 8))
#define MAP_VERDANTURF_TOWN_POKEMON_CENTER_2F       (5 | (6 << 8))
#define MAP_VERDANTURF_TOWN_WANDAS_HOUSE            (6 | (6 << 8))
#define MAP_VERDANTURF_TOWN_FRIENDSHIP_RATERS_HOUSE (7 | (6 << 8))
#define MAP_VERDANTURF_TOWN_HOUSE                   (8 | (6 << 8))

// Map Group 7
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_1F (0 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_POKEMON_CENTER_2F (1 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE1            (2 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE2            (3 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE3            (4 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE4            (5 | (7 << 8))
#define MAP_PACIFIDLOG_TOWN_HOUSE5            (6 | (7 << 8))

// Map Group 8
#define MAP_PETALBURG_CITY_WALLYS_HOUSE      (0 | (8 << 8))
#define MAP_PETALBURG_CITY_GYM               (1 | (8 << 8))
#define MAP_PETALBURG_CITY_HOUSE1            (2 | (8 << 8))
#define MAP_PETALBURG_CITY_HOUSE2            (3 | (8 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_1F (4 | (8 << 8))
#define MAP_PETALBURG_CITY_POKEMON_CENTER_2F (5 | (8 << 8))
#define MAP_PETALBURG_CITY_MART              (6 | (8 << 8))

// Map Group 9

// Map Group 10
#define MAP_MAUVILLE_CITY_GYM               (0 | (10 << 8))
#define MAP_MAUVILLE_CITY_BIKE_SHOP         (1 | (10 << 8))
#define MAP_MAUVILLE_CITY_HOUSE1            (2 | (10 << 8))
#define MAP_MAUVILLE_CITY_GAME_CORNER       (3 | (10 << 8))
#define MAP_MAUVILLE_CITY_HOUSE2            (4 | (10 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_1F (5 | (10 << 8))
#define MAP_MAUVILLE_CITY_POKEMON_CENTER_2F (6 | (10 << 8))
#define MAP_MAUVILLE_CITY_MART              (7 | (10 << 8))

// Map Group 11
#define MAP_RUSTBORO_CITY_DEVON_CORP_1F     (0 | (11 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_2F     (1 | (11 << 8))
#define MAP_RUSTBORO_CITY_DEVON_CORP_3F     (2 | (11 << 8))
#define MAP_RUSTBORO_CITY_GYM               (3 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_SCHOOL    (4 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_1F (5 | (11 << 8))
#define MAP_RUSTBORO_CITY_POKEMON_CENTER_2F (6 | (11 << 8))
#define MAP_RUSTBORO_CITY_MART              (7 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_1F          (8 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT1_2F          (9 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE1            (10 | (11 << 8))
#define MAP_RUSTBORO_CITY_CUTTERS_HOUSE     (11 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE2            (12 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_1F          (13 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_2F          (14 | (11 << 8))
#define MAP_RUSTBORO_CITY_FLAT2_3F          (15 | (11 << 8))
#define MAP_RUSTBORO_CITY_HOUSE3            (16 | (11 << 8))

// Map Group 12
#define MAP_FORTREE_CITY_HOUSE1            (0 | (12 << 8))
#define MAP_FORTREE_CITY_GYM               (1 | (12 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_1F (2 | (12 << 8))
#define MAP_FORTREE_CITY_POKEMON_CENTER_2F (3 | (12 << 8))
#define MAP_FORTREE_CITY_MART              (4 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE2            (5 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE3            (6 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE4            (7 | (12 << 8))
#define MAP_FORTREE_CITY_HOUSE5            (8 | (12 << 8))
#define MAP_FORTREE_CITY_DECORATION_SHOP   (9 | (12 << 8))

// Map Group 13
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_1F        (0 | (13 << 8))
#define MAP_LILYCOVE_CITY_COVE_LILY_MOTEL_2F        (1 | (13 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_1F        (2 | (13 << 8))
#define MAP_LILYCOVE_CITY_LILYCOVE_MUSEUM_2F        (3 | (13 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_LOBBY             (4 | (13 << 8))
#define MAP_LILYCOVE_CITY_CONTEST_HALL              (5 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_1F         (6 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_CENTER_2F         (7 | (13 << 8))
#define MAP_LILYCOVE_CITY_UNUSED_MART               (8 | (13 << 8))
#define MAP_LILYCOVE_CITY_POKEMON_TRAINER_FAN_CLUB  (9 | (13 << 8))
#define MAP_LILYCOVE_CITY_HARBOR                    (10 | (13 << 8))
#define MAP_LILYCOVE_CITY_MOVE_DELETERS_HOUSE       (11 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE1                    (12 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE2                    (13 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE3                    (14 | (13 << 8))
#define MAP_LILYCOVE_CITY_HOUSE4                    (15 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_1F       (16 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_2F       (17 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_3F       (18 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_4F       (19 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_5F       (20 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ROOFTOP  (21 | (13 << 8))
#define MAP_LILYCOVE_CITY_DEPARTMENT_STORE_ELEVATOR (22 | (13 << 8))

// Map Group 14
#define MAP_MOSSDEEP_CITY_GYM               (0 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE1            (1 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE2            (2 | (14 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_1F (3 | (14 << 8))
#define MAP_MOSSDEEP_CITY_POKEMON_CENTER_2F (4 | (14 << 8))
#define MAP_MOSSDEEP_CITY_MART              (5 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE3            (6 | (14 << 8))
#define MAP_MOSSDEEP_CITY_STEVENS_HOUSE     (7 | (14 << 8))
#define MAP_MOSSDEEP_CITY_HOUSE4            (8 | (14 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_1F   (9 | (14 << 8))
#define MAP_MOSSDEEP_CITY_SPACE_CENTER_2F   (10 | (14 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_1F    (11 | (14 << 8))
#define MAP_MOSSDEEP_CITY_GAME_CORNER_B1F   (12 | (14 << 8))

// Map Group 15

// Map Group 16
#define MAP_EVER_GRANDE_CITY_SIDNEYS_ROOM      (0 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_PHOEBES_ROOM      (1 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_GLACIAS_ROOM      (2 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_DRAKES_ROOM       (3 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_CHAMPIONS_ROOM    (4 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL1             (5 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL2             (6 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL3             (7 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL4             (8 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL5             (9 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_1F (10 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_HALL_OF_FAME      (11 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_1F (12 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_CENTER_2F (13 | (16 << 8))
#define MAP_EVER_GRANDE_CITY_POKEMON_LEAGUE_2F (14 | (16 << 8))

// Map Group 17
#define MAP_ROUTE104_MR_BRINEYS_HOUSE         (0 | (17 << 8))
#define MAP_ROUTE104_PRETTY_PETAL_FLOWER_SHOP (1 | (17 << 8))

// Map Group 18
#define MAP_ROUTE111_WINSTRATE_FAMILYS_HOUSE (0 | (18 << 8))
#define MAP_ROUTE111_OLD_LADYS_REST_STOP     (1 | (18 << 8))

// Map Group 19
#define MAP_ROUTE112_CABLE_CAR_STATION   (0 | (19 << 8))
#define MAP_MT_CHIMNEY_CABLE_CAR_STATION (1 | (19 << 8))

// Map Group 20
#define MAP_ROUTE114_FOSSIL_MANIACS_HOUSE  (0 | (20 << 8))
#define MAP_ROUTE114_FOSSIL_MANIACS_TUNNEL (1 | (20 << 8))
#define MAP_ROUTE114_LANETTES_HOUSE        (2 | (20 << 8))

// Map Group 21
#define MAP_ROUTE116_TUNNELERS_REST_HOUSE (0 | (21 << 8))

// Map Group 22
#define MAP_ROUTE117_POKEMON_DAY_CARE (0 | (22 << 8))

// Map Group 23
#define MAP_ROUTE121_SAFARI_ZONE_ENTRANCE (0 | (23 << 8))

// Map Group 24
#define MAP_METEOR_FALLS_1F_1R                 (0 | (24 << 8))
#define MAP_METEOR_FALLS_1F_2R                 (1 | (24 << 8))
#define MAP_METEOR_FALLS_B1F_1R                (2 | (24 << 8))
#define MAP_METEOR_FALLS_B1F_2R                (3 | (24 << 8))
#define MAP_RUSTURF_TUNNEL                     (4 | (24 << 8))
#define MAP_DESERT_RUINS                       (5 | (24 << 8))
#define MAP_GRANITE_CAVE_1F                    (6 | (24 << 8))
#define MAP_GRANITE_CAVE_B1F                   (7 | (24 << 8))
#define MAP_GRANITE_CAVE_B2F                   (8 | (24 << 8))
#define MAP_GRANITE_CAVE_STEVENS_ROOM          (9 | (24 << 8))
#define MAP_PETALBURG_WOODS                    (10 | (24 << 8))
#define MAP_MT_CHIMNEY                         (11 | (24 << 8))
#define MAP_JAGGED_PASS                        (12 | (24 << 8))
#define MAP_FIERY_PATH                         (13 | (24 << 8))
#define MAP_MT_PYRE_1F                         (14 | (24 << 8))
#define MAP_MT_PYRE_2F                         (15 | (24 << 8))
#define MAP_MT_PYRE_3F                         (16 | (24 << 8))
#define MAP_MT_PYRE_4F                         (17 | (24 << 8))
#define MAP_MT_PYRE_5F                         (18 | (24 << 8))
#define MAP_MT_PYRE_6F                         (19 | (24 << 8))
#define MAP_MT_PYRE_EXTERIOR                   (20 | (24 << 8))
#define MAP_MT_PYRE_SUMMIT                     (21 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ENTRANCE           (22 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM1              (23 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM2              (24 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM3              (25 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM4              (26 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM5              (27 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM6              (28 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM7              (29 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM8              (30 | (24 << 8))
#define MAP_SEAFLOOR_CAVERN_ROOM9              (31 | (24 << 8))
#define MAP_VICTORY_ROAD_1F                    (32 | (24 << 8))
#define MAP_VICTORY_ROAD_B1F                   (33 | (24 << 8))
#define MAP_VICTORY_ROAD_B2F                   (34 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM  (35 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM     (36 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM    (37 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM     (38 | (24 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_ENTRANCE_ROOM (39 | (24 << 8))
#define MAP_SHOAL_CAVE_HIGH_TIDE_INNER_ROOM    (40 | (24 << 8))
#define MAP_NEW_MAUVILLE_ENTRANCE              (41 | (24 << 8))
#define MAP_NEW_MAUVILLE_INSIDE                (42 | (24 << 8))
#define MAP_ISLAND_CAVE                        (43 | (24 << 8))
#define MAP_ANCIENT_TOMB                       (44 | (24 << 8))
#define MAP_SEALED_CHAMBER_OUTER_ROOM          (45 | (24 << 8))
#define MAP_SEALED_CHAMBER_INNER_ROOM          (46 | (24 << 8))
#define MAP_SCORCHED_SLAB                      (47 | (24 << 8))
#define MAP_SKY_PILLAR_ENTRANCE                (48 | (24 << 8))
#define MAP_SKY_PILLAR_OUTSIDE                 (49 | (24 << 8))
#define MAP_SKY_PILLAR_1F                      (50 | (24 << 8))
#define MAP_SKY_PILLAR_2F                      (51 | (24 << 8))
#define MAP_SKY_PILLAR_3F                      (52 | (24 << 8))
#define MAP_SKY_PILLAR_4F                      (53 | (24 << 8))
#define MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM       (54 | (24 << 8))
#define MAP_SKY_PILLAR_5F                      (55 | (24 << 8))
#define MAP_SKY_PILLAR_TOP                     (56 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_1F                   (57 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_2F_1R                (58 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_2F_2R                (59 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_3F_1R                (60 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_3F_2R                (61 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_4F                   (62 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_3F_3R                (63 | (24 << 8))
#define MAP_MAGMA_HIDEOUT_2F_3R                (64 | (24 << 8))
#define MAP_MIRAGE_TOWER_1F                    (65 | (24 << 8))
#define MAP_MIRAGE_TOWER_2F                    (66 | (24 << 8))
#define MAP_MIRAGE_TOWER_3F                    (67 | (24 << 8))
#define MAP_MIRAGE_TOWER_4F                    (68 | (24 << 8))
#define MAP_DESERT_UNDERPASS                   (69 | (24 << 8))
#define MAP_ARTISAN_CAVE_B1F                   (70 | (24 << 8))
#define MAP_ARTISAN_CAVE_1F                    (71 | (24 << 8))
#define MAP_MARINE_CAVE_ENTRANCE               (72 | (24 << 8))
#define MAP_MARINE_CAVE_END                    (73 | (24 << 8))
#define MAP_TERRA_CAVE_ENTRANCE                (74 | (24 << 8))
#define MAP_TERRA_CAVE_END                     (75 | (24 << 8))
#define MAP_ALTERING_CAVE                      (76 | (24 << 8))
#define MAP_METEOR_FALLS_STEVENS_CAVE          (77 | (24 << 8))

// Map Group 25
#define MAP_SECRET_BASE_RED_CAVE1           (0 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE1         (1 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE1          (2 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE1        (3 | (25 << 8))
#define MAP_SECRET_BASE_TREE1               (4 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB1              (5 | (25 << 8))
#define MAP_SECRET_BASE_RED_CAVE2           (6 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE2         (7 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE2          (8 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE2        (9 | (25 << 8))
#define MAP_SECRET_BASE_TREE2               (10 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB2              (11 | (25 << 8))
#define MAP_SECRET_BASE_RED_CAVE3           (12 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE3         (13 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE3          (14 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE3        (15 | (25 << 8))
#define MAP_SECRET_BASE_TREE3               (16 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB3              (17 | (25 << 8))
#define MAP_SECRET_BASE_RED_CAVE4           (18 | (25 << 8))
#define MAP_SECRET_BASE_BROWN_CAVE4         (19 | (25 << 8))
#define MAP_SECRET_BASE_BLUE_CAVE4          (20 | (25 << 8))
#define MAP_SECRET_BASE_YELLOW_CAVE4        (21 | (25 << 8))
#define MAP_SECRET_BASE_TREE4               (22 | (25 << 8))
#define MAP_SECRET_BASE_SHRUB4              (23 | (25 << 8))
#define MAP_BATTLE_COLOSSEUM_2P             (24 | (25 << 8))
#define MAP_TRADE_CENTER                    (25 | (25 << 8))
#define MAP_RECORD_CORNER                   (26 | (25 << 8))
#define MAP_BATTLE_COLOSSEUM_4P             (27 | (25 << 8))
#define MAP_CONTEST_HALL                    (28 | (25 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_29 (29 | (25 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_30 (30 | (25 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_31 (31 | (25 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_32 (32 | (25 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_33 (33 | (25 << 8))
#define MAP_UNKNOWN_LINK_CONTEST_ROOM_25_34 (34 | (25 << 8))
#define MAP_CONTEST_HALL_BEAUTY             (35 | (25 << 8))
#define MAP_CONTEST_HALL_TOUGH              (36 | (25 << 8))
#define MAP_CONTEST_HALL_COOL               (37 | (25 << 8))
#define MAP_CONTEST_HALL_SMART              (38 | (25 << 8))
#define MAP_CONTEST_HALL_CUTE               (39 | (25 << 8))
#define MAP_INSIDE_OF_TRUCK                 (40 | (25 << 8))
#define MAP_SS_TIDAL_CORRIDOR               (41 | (25 << 8))
#define MAP_SS_TIDAL_LOWER_DECK             (42 | (25 << 8))
#define MAP_SS_TIDAL_ROOMS                  (43 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE01         (44 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE02         (45 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE03         (46 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE04         (47 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE05         (48 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE06         (49 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE07         (50 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE08         (51 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE09         (52 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE10         (53 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE11         (54 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE12         (55 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE13         (56 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE14         (57 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE15         (58 | (25 << 8))
#define MAP_BATTLE_PYRAMID_SQUARE16         (59 | (25 << 8))
#define MAP_UNION_ROOM                      (60 | (25 << 8))

// Map Group 26
#define MAP_SAFARI_ZONE_NORTHWEST                           (0 | (26 << 8))
#define MAP_SAFARI_ZONE_NORTH                               (1 | (26 << 8))
#define MAP_SAFARI_ZONE_SOUTHWEST                           (2 | (26 << 8))
#define MAP_SAFARI_ZONE_SOUTH                               (3 | (26 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_WEST                    (4 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_LOBBY              (5 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_ELEVATOR           (6 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_CORRIDOR           (7 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_BATTLE_ROOM        (8 | (26 << 8))
#define MAP_SOUTHERN_ISLAND_EXTERIOR                        (9 | (26 << 8))
#define MAP_SOUTHERN_ISLAND_INTERIOR                        (10 | (26 << 8))
#define MAP_SAFARI_ZONE_REST_HOUSE                          (11 | (26 << 8))
#define MAP_SAFARI_ZONE_NORTHEAST                           (12 | (26 << 8))
#define MAP_SAFARI_ZONE_SOUTHEAST                           (13 | (26 << 8))
#define MAP_BATTLE_FRONTIER_OUTSIDE_EAST                    (14 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_PARTNER_ROOM (15 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_CORRIDOR     (16 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_TOWER_MULTI_BATTLE_ROOM  (17 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_LOBBY               (18 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_CORRIDOR            (19 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_PRE_BATTLE_ROOM     (20 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_DOME_BATTLE_ROOM         (21 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_LOBBY             (22 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_CORRIDOR          (23 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PALACE_BATTLE_ROOM       (24 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_LOBBY            (25 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_FLOOR            (26 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PYRAMID_TOP              (27 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_LOBBY              (28 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_CORRIDOR           (29 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_ARENA_BATTLE_ROOM        (30 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_LOBBY            (31 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_PRE_BATTLE_ROOM  (32 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_FACTORY_BATTLE_ROOM      (33 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_LOBBY               (34 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_CORRIDOR            (35 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_THREE_PATH_ROOM     (36 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_NORMAL         (37 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_FINAL          (38 | (26 << 8))
#define MAP_BATTLE_FRONTIER_BATTLE_PIKE_ROOM_WILD_MONS      (39 | (26 << 8))
#define MAP_BATTLE_FRONTIER_RANKING_HALL                    (40 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE1                         (41 | (26 << 8))
#define MAP_BATTLE_FRONTIER_EXCHANGE_SERVICE_CORNER         (42 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE2                         (43 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE3                         (44 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE4                         (45 | (26 << 8))
#define MAP_BATTLE_FRONTIER_SCOTTS_HOUSE                    (46 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE5                         (47 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE6                         (48 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE7                         (49 | (26 << 8))
#define MAP_BATTLE_FRONTIER_RECEPTION_GATE                  (50 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE8                         (51 | (26 << 8))
#define MAP_BATTLE_FRONTIER_LOUNGE9                         (52 | (26 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_1F               (53 | (26 << 8))
#define MAP_BATTLE_FRONTIER_POKEMON_CENTER_2F               (54 | (26 << 8))
#define MAP_BATTLE_FRONTIER_MART                            (55 | (26 << 8))
#define MAP_FARAWAY_ISLAND_ENTRANCE                         (56 | (26 << 8))
#define MAP_FARAWAY_ISLAND_INTERIOR                         (57 | (26 << 8))
#define MAP_BIRTH_ISLAND_EXTERIOR                           (58 | (26 << 8))
#define MAP_BIRTH_ISLAND_HARBOR                             (59 | (26 << 8))
#define MAP_TRAINER_HILL_ENTRANCE                           (60 | (26 << 8))
#define MAP_TRAINER_HILL_1F                                 (61 | (26 << 8))
#define MAP_TRAINER_HILL_2F                                 (62 | (26 << 8))
#define MAP_TRAINER_HILL_3F                                 (63 | (26 << 8))
#define MAP_TRAINER_HILL_4F                                 (64 | (26 << 8))
#define MAP_TRAINER_HILL_ROOF                               (65 | (26 << 8))
#define MAP_NAVEL_ROCK_EXTERIOR                             (66 | (26 << 8))
#define MAP_NAVEL_ROCK_HARBOR                               (67 | (26 << 8))
#define MAP_NAVEL_ROCK_ENTRANCE                             (68 | (26 << 8))
#define MAP_NAVEL_ROCK_B1F                                  (69 | (26 << 8))
#define MAP_NAVEL_ROCK_FORK                                 (70 | (26 << 8))
#define MAP_NAVEL_ROCK_UP1                                  (71 | (26 << 8))
#define MAP_NAVEL_ROCK_UP2                                  (72 | (26 << 8))
#define MAP_NAVEL_ROCK_UP3                                  (73 | (26 << 8))
#define MAP_NAVEL_ROCK_UP4                                  (74 | (26 << 8))
#define MAP_NAVEL_ROCK_TOP                                  (75 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN01                               (76 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN02                               (77 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN03                               (78 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN04                               (79 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN05                               (80 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN06                               (81 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN07                               (82 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN08                               (83 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN09                               (84 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN10                               (85 | (26 << 8))
#define MAP_NAVEL_ROCK_DOWN11                               (86 | (26 << 8))
#define MAP_NAVEL_ROCK_BOTTOM                               (87 | (26 << 8))
#define MAP_TRAINER_HILL_ELEVATOR                           (88 | (26 << 8))

// Map Group 27
#define MAP_ROUTE104_PROTOTYPE                          (0 | (27 << 8))
#define MAP_ROUTE104_PROTOTYPE_PRETTY_PETAL_FLOWER_SHOP (1 | (27 << 8))

// Map Group 28
#define MAP_ROUTE109_SEASHORE_HOUSE (0 | (28 << 8))

// Map Group 29
#define MAP_ROUTE110_TRICK_HOUSE_ENTRANCE                (0 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_END                     (1 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_CORRIDOR                (2 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE1                 (3 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE2                 (4 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE3                 (5 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE4                 (6 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE5                 (7 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE6                 (8 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE7                 (9 | (29 << 8))
#define MAP_ROUTE110_TRICK_HOUSE_PUZZLE8                 (10 | (29 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_NORTH_ENTRANCE (11 | (29 << 8))
#define MAP_ROUTE110_SEASIDE_CYCLING_ROAD_SOUTH_ENTRANCE (12 | (29 << 8))

// Map Group 30
#define MAP_ROUTE113_GLASS_WORKSHOP (0 | (30 << 8))

// Map Group 31
#define MAP_ROUTE123_BERRY_MASTERS_HOUSE (0 | (31 << 8))

// Map Group 32
#define MAP_ROUTE119_WEATHER_INSTITUTE_1F (0 | (32 << 8))
#define MAP_ROUTE119_WEATHER_INSTITUTE_2F (1 | (32 << 8))
#define MAP_ROUTE119_HOUSE                (2 | (32 << 8))

// Map Group 33
#define MAP_ROUTE124_DIVING_TREASURE_HUNTERS_HOUSE (0 | (33 << 8))
#define MAP_POKESCAPE_BATTLE_TOWER_BATTLE_ROOM     (1 | (33 << 8))

// Map Group 34
#define MAP_TUTORIAL_ISLAND   (0 | (34 << 8))
#define MAP_LUMBRIDGE         (1 | (34 << 8))
#define MAP_DRAYNOR           (2 | (34 << 8))
#define MAP_PORT_SARIM        (3 | (34 << 8))
#define MAP_RIMMINGTON        (4 | (34 << 8))
#define MAP_FALADOR           (5 | (34 << 8))
#define MAP_VARROCK           (6 | (34 << 8))
#define MAP_VARROCK_NORTH     (7 | (34 << 8))
#define MAP_BARBARIAN_VILLAGE (8 | (34 << 8))
#define MAP_GOBLIN_VILLAGE    (9 | (34 << 8))
#define MAP_DWARVEN_MINES     (10 | (34 << 8))
#define MAP_EDGEVILLE         (11 | (34 << 8))
#define MAP_AL_KHARID         (12 | (34 << 8))
#define MAP_MUSA_POINT        (13 | (34 << 8))
#define MAP_TAVERLEY          (14 | (34 << 8))
#define MAP_LUMBRIDGE_SWAMP   (15 | (34 << 8))
#define MAP_MILL_LANE_MILL    (16 | (34 << 8))
#define MAP_DRAYNOR_MANOR     (17 | (34 << 8))
#define MAP_MUDSKIPPER_POINT  (18 | (34 << 8))
#define MAP_WIZARDS_TOWER     (19 | (34 << 8))

// Map Group 35
#define MAP_ROUTE1  (0 | (35 << 8))
#define MAP_ROUTE2  (1 | (35 << 8))
#define MAP_ROUTE3  (2 | (35 << 8))
#define MAP_ROUTE4  (3 | (35 << 8))
#define MAP_ROUTE5  (4 | (35 << 8))
#define MAP_ROUTE6  (5 | (35 << 8))
#define MAP_ROUTE7  (6 | (35 << 8))
#define MAP_ROUTE8  (7 | (35 << 8))
#define MAP_ROUTE9  (8 | (35 << 8))
#define MAP_ROUTE10 (9 | (35 << 8))
#define MAP_ROUTE11 (10 | (35 << 8))
#define MAP_ROUTE12 (11 | (35 << 8))
#define MAP_ROUTE13 (12 | (35 << 8))
#define MAP_ROUTE14 (13 | (35 << 8))
#define MAP_ROUTE15 (14 | (35 << 8))
#define MAP_ROUTE16 (15 | (35 << 8))
#define MAP_ROUTE17 (16 | (35 << 8))
#define MAP_ROUTE18 (17 | (35 << 8))
#define MAP_ROUTE19 (18 | (35 << 8))
#define MAP_ROUTE20 (19 | (35 << 8))
#define MAP_ROUTE21 (20 | (35 << 8))
#define MAP_ROUTE22 (21 | (35 << 8))
#define MAP_ROUTE23 (22 | (35 << 8))
#define MAP_ROUTE24 (23 | (35 << 8))
#define MAP_ROUTE25 (24 | (35 << 8))
#define MAP_ROUTE26 (25 | (35 << 8))
#define MAP_ROUTE27 (26 | (35 << 8))
#define MAP_ROUTE28 (27 | (35 << 8))
#define MAP_ROUTE29 (28 | (35 << 8))
#define MAP_ROUTE30 (29 | (35 << 8))
#define MAP_ROUTE31 (30 | (35 << 8))
#define MAP_ROUTE32 (31 | (35 << 8))
#define MAP_ROUTE33 (32 | (35 << 8))
#define MAP_ROUTE34 (33 | (35 << 8))
#define MAP_ROUTE35 (34 | (35 << 8))
#define MAP_ROUTE36 (35 | (35 << 8))
#define MAP_ROUTE37 (36 | (35 << 8))
#define MAP_ROUTE38 (37 | (35 << 8))
#define MAP_ROUTE39 (38 | (35 << 8))
#define MAP_ROUTE40 (39 | (35 << 8))
#define MAP_ROUTE41 (40 | (35 << 8))
#define MAP_ROUTE42 (41 | (35 << 8))
#define MAP_ROUTE43 (42 | (35 << 8))

// Map Group 36
#define MAP_TUTORIAL_ISLAND_CAVE       (0 | (36 << 8))
#define MAP_LUMBRIDGE_FOREST           (1 | (36 << 8))
#define MAP_UNDERWATER_LUMBRIDGE       (2 | (36 << 8))
#define MAP_AL_KHARID_MINES_B1F        (3 | (36 << 8))
#define MAP_AL_KHARID_MINES_B2F        (4 | (36 << 8))
#define MAP_KALPHITE_CAVES_B1F         (5 | (36 << 8))
#define MAP_KALPHITE_CAVES_B2F         (6 | (36 << 8))
#define MAP_KALPHITE_CAVES_B3F         (7 | (36 << 8))
#define MAP_KALPHITE_CAVES_B4F         (8 | (36 << 8))
#define MAP_GIANT_MOLE_CAVE            (9 | (36 << 8))
#define MAP_DWARVEN_MINE_B1F           (10 | (36 << 8))
#define MAP_KING_BLACK_DRAGON_LAIR     (11 | (36 << 8))
#define MAP_KING_BLACK_DRAGON_B1F      (12 | (36 << 8))
#define MAP_KING_BLACK_DRAGON_B2F      (13 | (36 << 8))
#define MAP_QUEEN_BLACK_DRAGON_LAIR    (14 | (36 << 8))
#define MAP_LUMBRIDGE_SWAMP_CAVES      (15 | (36 << 8))
#define MAP_LUMBRIDGE_SWAMP_CAVES_JUNA (16 | (36 << 8))
#define MAP_DWARVEN_MINE_B2F           (17 | (36 << 8))
#define MAP_VORAGO_CAVERN              (18 | (36 << 8))
#define MAP_CHAOS_TUNNELS_B1F          (19 | (36 << 8))
#define MAP_ABYSSAL_REALM_1            (20 | (36 << 8))
#define MAP_ABYSSAL_REALM_2            (21 | (36 << 8))
#define MAP_KARAMJA_VOLCANO_B1F        (22 | (36 << 8))
#define MAP_KARAMJA_VOLCANO_B2F        (23 | (36 << 8))
#define MAP_KARAMJA_VOLCANO_B3F        (24 | (36 << 8))

// Map Group 37
#define MAP_TUTORIAL_ISLAND_LAB_UP   (0 | (37 << 8))
#define MAP_TUTORIAL_ISLAND_LAB_DOWN (1 | (37 << 8))
#define MAP_TUTORIAL_ISLAND_SHOP     (2 | (37 << 8))
#define MAP_TUTORIAL_ISLAND_CHURCH   (3 | (37 << 8))

// Map Group 38
#define MAP_LUMBRIDGE_HOUSE_BOBS_AXES1 (0 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_BOBS_AXES2 (1 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_1          (2 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_2          (3 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_RODDECK1   (4 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_RODDECK2   (5 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_STARTER1   (6 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_STARTER2   (7 | (38 << 8))
#define MAP_LUMBRIDGE_GENERAL_STORE    (8 | (38 << 8))
#define MAP_LUMBRIDGE_GENERAL_STORE2   (9 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_3          (10 | (38 << 8))
#define MAP_LUMBRIDGE_BANK             (11 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_4          (12 | (38 << 8))
#define MAP_LUMBRIDGE_CASTLE_1         (13 | (38 << 8))
#define MAP_LUMBRIDGE_CASTLE_2         (14 | (38 << 8))
#define MAP_LUMBRIDGE_CASTLE_3         (15 | (38 << 8))
#define MAP_LUMBRIDGE_CASTLE_4         (16 | (38 << 8))
#define MAP_POTTERINGTON_FARM_INTERIOR (17 | (38 << 8))
#define MAP_LUMBRIDGE_HOUSE_3_2F       (18 | (38 << 8))
#define MAP_LUMBRIDGE_CHURCH           (19 | (38 << 8))

// Map Group 39
#define MAP_DRAYNOR_HOUSE_MORGAN_1F (0 | (39 << 8))
#define MAP_DRAYNOR_HOUSE_MORGAN_2F (1 | (39 << 8))
#define MAP_DRAYNOR_HOUSE_WO_M_1F   (2 | (39 << 8))
#define MAP_DRAYNOR_HOUSE_WO_M_2F   (3 | (39 << 8))
#define MAP_DRAYNOR_BANK            (4 | (39 << 8))
#define MAP_DRAYNOR_SEWERS_1        (5 | (39 << 8))
#define MAP_DRAYNOR_SEWERS_2        (6 | (39 << 8))
#define MAP_DRAYNOR_SEWERS_3        (7 | (39 << 8))
#define MAP_DRAYNOR_SEWERS_4        (8 | (39 << 8))

// Map Group 40
#define MAP_PORT_SARIM_PUB_1F (0 | (40 << 8))
#define MAP_PORT_SARIM_PUB_2F (1 | (40 << 8))

// Map Group 41

// Map Group 42
#define MAP_FALADOR_HAIRDRESSERS    (0 | (42 << 8))
#define MAP_FALADOR_HAIRDRESSERS_2F (1 | (42 << 8))
#define MAP_FALADOR_CASTLEYARD      (2 | (42 << 8))
#define MAP_FALADOR_BANK_WEST_1F    (3 | (42 << 8))
#define MAP_FALADOR_GEM_SHOP        (4 | (42 << 8))
#define MAP_FALADOR_PUB_1F          (5 | (42 << 8))
#define MAP_FALADOR_PUB_2F          (6 | (42 << 8))
#define MAP_FALADOR_BANK_EAST       (7 | (42 << 8))

// Map Group 43
#define MAP_VARROCK_THESSALIA_SHOP    (0 | (43 << 8))
#define MAP_VARROCK_THESSALIA_SHOP_UP (1 | (43 << 8))
#define MAP_VARROCK_LOWE_SHOP         (2 | (43 << 8))
#define MAP_VARROCK_LOWE_SHOP_UP      (3 | (43 << 8))
#define MAP_VARROCK_HOUSE_1           (4 | (43 << 8))
#define MAP_VARROCK_HOUSE_1_UP        (5 | (43 << 8))
#define MAP_VARROCK_HOUSE_2           (6 | (43 << 8))
#define MAP_VARROCK_HOUSE_3           (7 | (43 << 8))
#define MAP_VARROCK_HOUSE_4           (8 | (43 << 8))
#define MAP_VARROCK_BANK_EAST         (9 | (43 << 8))
#define MAP_VARROCK_BANK_EAST_UP      (10 | (43 << 8))
#define MAP_VARROCK_WEAPON_SHOP       (11 | (43 << 8))
#define MAP_VARROCK_WEAPON_SHOP_UP    (12 | (43 << 8))
#define MAP_VARROCK_BANK_WEST         (13 | (43 << 8))
#define MAP_VARROCK_BANK_WEST_B1F     (14 | (43 << 8))
#define MAP_VARROCK_PUB_1F            (15 | (43 << 8))
#define MAP_VARROCK_PUB_2F            (16 | (43 << 8))
#define MAP_VARROCK_SEWERS_1F         (17 | (43 << 8))
#define MAP_VARROCK_SEWERS_2F         (18 | (43 << 8))

// Map Group 44

// Map Group 45

// Map Group 46

// Map Group 47

// Map Group 48
#define MAP_YANILLE      (0 | (48 << 8))
#define MAP_ARDOUGNE     (1 | (48 << 8))
#define MAP_ROUTE50      (2 | (48 << 8))
#define MAP_ROUTE51      (3 | (48 << 8))
#define MAP_ROUTE52      (4 | (48 << 8))
#define MAP_ROUTE53      (5 | (48 << 8))
#define MAP_ROUTE54      (6 | (48 << 8))
#define MAP_PORT_KHAZARD (7 | (48 << 8))
#define MAP_RELLEKKA     (8 | (48 << 8))

// Map Group 49
#define MAP_TZHAAR_1F          (0 | (49 << 8))
#define MAP_TZHAAR_FIGHT_CAVES (1 | (49 << 8))
#define MAP_TZHAAR_CAVES_1     (2 | (49 << 8))

// Map Group 50
#define MAP_ROUTE1_HOUSE_FRED         (0 | (50 << 8))
#define MAP_ROUTE1_HOUSE_1            (1 | (50 << 8))
#define MAP_MILL_LANE_MILL_1          (2 | (50 << 8))
#define MAP_MILL_LANE_MILL_2          (3 | (50 << 8))
#define MAP_MILL_LANE_MILL_3          (4 | (50 << 8))
#define MAP_WIZARDS_TOWER_B1F         (5 | (50 << 8))
#define MAP_WIZARDS_TOWER_1F          (6 | (50 << 8))
#define MAP_WIZARDS_TOWER_2F          (7 | (50 << 8))
#define MAP_WIZARDS_TOWER_3F          (8 | (50 << 8))
#define MAP_WIZARDS_TOWER_ATTIC       (9 | (50 << 8))
#define MAP_WIZARDS_TOWER_DINING_HALL (10 | (50 << 8))
#define MAP_DRAYNOR_MANOR_1F          (11 | (50 << 8))
#define MAP_DRAYNOR_MANOR_2F          (12 | (50 << 8))
#define MAP_DRAYNOR_MANOR_3F          (13 | (50 << 8))
#define MAP_DRAYNOR_MANOR_B1F         (14 | (50 << 8))
#define MAP_DRAYNOR_MANOR_CRYPT       (15 | (50 << 8))
#define MAP_JOLLY_BOAR_PUB_1F         (16 | (50 << 8))
#define MAP_JOLLY_BOAR_PUB_2F         (17 | (50 << 8))
#define MAP_YANILLE_PUB_1F            (18 | (50 << 8))
#define MAP_YANILLE_PUB_2F            (19 | (50 << 8))
#define MAP_POISON_ARROW_PUB_1F       (20 | (50 << 8))
#define MAP_FLYING_HORSE_PUB_1F       (21 | (50 << 8))
#define MAP_FLYING_HORSE_PUB_2F       (22 | (50 << 8))
#define MAP_HAM_HIDEOUT_B1F           (23 | (50 << 8))
#define MAP_HAM_HIDEOUT_B2F           (24 | (50 << 8))
#define MAP_MODERATOR_LOBBY           (25 | (50 << 8))
#define MAP_POISON_WASTE_SEWERS_1F    (26 | (50 << 8))
#define MAP_SINKHOLE_1                (27 | (50 << 8))

#define MAP_GROUPS_COUNT 51

#endif // GUARD_CONSTANTS_MAP_GROUPS_H
