ProfBirch_EventScript_UpdateLocation:: @ 82720AD

	return

ProfBirch_EventScript_MoveToLab:: @ 827211A

	return

ProfBirch_EventScript_MoveToRoute101:: @ 8272127

	return

ProfBirch_EventScript_MoveToRoute103:: @ 8272134

	return

ProfBirch_EventScript_RatePokedexOrRegister:: @ 8272141
	end

ProfBirch_EventScript_AskRatePokedex:: @ 8272155

	end

ProfBirch_EventScript_DeclineRating:: @ 827216F

	end

ProfBirch_EventScript_ShowRatingMessage:: @ 8272179

	return

ProfBirch_EventScript_RatePokedex:: @ 8272184

	return
